import type { ComponentProps } from "react";
import { Icon } from "@iconify/react";
import {
  Moon,
  Sun,
  ListMinus,
  ExternalLink,
  X,
  Eye,
  EyeOff,
  CheckCircle2,
  ChevronLeft,
  ChevronRight,
  Check,
  ChevronDown,
  User,
  ChevronUp,
  Info,
  Globe,
  ArrowRight,
  ArrowLeft,
  Mail,
  Lock,
  Pencil,
  MailCheck,
  File,
  Calendar,
  User2,
  Trash2,
  Timer,
  Link,
  LogOut,
  PieChart,
  ClipboardList,
  LayoutDashboard,
  Users,
  PlusSquare,
  House,
  Heart,
  AsteriskIcon,
  Send,
  Upload,
  CircleDot,
  EllipsisVertical,
} from "lucide-react";

type IconProps = Omit<ComponentProps<typeof Icon>, "icon">;
const FaFacebookF = (props: IconProps) => <Icon icon="fa-brands:facebook-f" {...props} />;
const FaLinkedinIn = (props: IconProps) => <Icon icon="mdi:linkedin" {...props} />;
const FaWhatsapp = (props: IconProps) => <Icon icon="fa-brands:whatsapp" {...props} />;
const FaTwitter = (props: IconProps) => <Icon icon="fa-brands:twitter" {...props} />;

export {
  Upload,
  Sun,
  Moon,
  ExternalLink,
  FaFacebookF,
  FaLinkedinIn,
  FaWhatsapp,
  FaTwitter,
  ListMinus,
  X,
  Info,
  Eye,
  EyeOff,
  CheckCircle2,
  ChevronLeft,
  ChevronDown,
  Globe,
  ChevronRight,
  Check,
  User,
  ChevronUp,
  ArrowRight,
  Mail,
  ArrowLeft,
  Pencil,
  MailCheck,
  Lock,
  File,
  Calendar,
  User2,
  Trash2,
  Timer,
  Link,
  LayoutDashboard,
  Users,
  ClipboardList,
  PieChart,
  LogOut,
  PlusSquare,
  House,
  Heart,
  AsteriskIcon,
  Send,
  CircleDot,
  EllipsisVertical,
};
